# Generated by Django 4.2.7 on 2024-02-25 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="code",
            field=models.CharField(blank=True, max_length=31, null=True),
        ),
    ]
