# Generated by Django 4.2.7 on 2024-02-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_role_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="photo",
            options={"ordering": ["is_main"]},
        ),
        migrations.AddField(
            model_name="photo",
            name="is_main",
            field=models.BooleanField(default=False),
        ),
    ]
